name: Lint

on: [push, pull_request]

jobs:
  lint-flake8-black:
    runs-on: ubuntu-latest
    name: flake8, black
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
      - name: black
        uses: psf/black@stable
