name: Lint

on: [push, pull_request]

jobs:
  lint-ruff:
    runs-on: ubuntu-latest
    name: ruff
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
